version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: cd circle_ci
      - run: flutter doctor
      - run: flutter test 
      - run: flutter -v build apk